---
- name: Create Code Server Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ code_server_data_directory }}"

- name: Code Server
  docker_container:
    name: code_server
    image: lscr.io/linuxserver/code-server:latest
    pull: true
    volumes:
      - "{{ code_server_data_directory }}:/config:rw"
    ports:
      - "{{ code_server_port }}:8443"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ code_server_user_id }}"
      PGID: "{{ code_server_group_id }}"
      PASSWORD: "{{ code_server_password }}"
      HASHED_PASSWORD: "{{ code_server_hashed_password }}"
      SUDO_PASSWORD: "{{ code_server_sudo_password }}"
      SUDO_PASSWORD_HASH: "{{ code_server_sudo_password_hash }}"

    restart_policy: unless-stopped
    memory: "{{ code_server_memory }}"
    labels:
      traefik.enable: "{{ code_server_available_externally }}"
      traefik.http.routers.code_server.rule: "Host(`{{ code_server_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.code_server.tls.certresolver: "letsencrypt"
      traefik.http.routers.code_server.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.code_server.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.code_server.loadbalancer.server.port: "8443"
